name: univers
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Univers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262827'
    - '#d1d1cf'
    - '#b4b6b3'
    - '#3e4243'
    - '#808483'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
