name: univers
favicon: null
layout_spectrum: 0.511775110848248
typography_spectrum: 0.11958466866053641
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2246329125482589
  lightness: 0.01505795051343739
  saturation: 0.3261503945104778
  rhythmicContrast: 0.33281760197132826
purpose: []
